server:
  port: 8071
spring:
  application:
    name: service-product
  datasource:
    url: jdbc:mysql://localhost:3306/test-cloud
    username: root
    password: jbw051201
rocketmq:
  name-server: 192.168.220.129:9876
