server:
  port: 8073
spring:
  application:
    name: service-order
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin的 请求地址
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1.0 #采样百分比
#  boot: #Springboot Admin的配置，由于actuator加不进来，配置它也没用
#    admin:
#      client:
#        url: http://localhost:8073
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
  sentinel:
    enabled: false # 不能开启哨兵功能，否则会报红：循环依赖
rocketmq:
  name-server:  192.168.220.129:9876
  producer:
    group: shop-order-test
#management:   #actuator的配置，但因为版本问题，一直不成功
#  endpoints:
#    web:
#      exposure:
#        include: * #由于默认只开放了 health、info 两个 API，其它 API 要正常使用，需将 exposure 配置项置为 *，才能正常使用 Actuator 暴露出来的接口
#  endpoint:
#    health:
#      show-details: always
